name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: list contents of the working directory
        run: ls

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Switch to deploy branch
        run: git checkout -B deploy

      - name: List contents of the working directory
        run: ls

      # - name: Copy build artifacts
      #   run: cp -r dist/* .

      # - name: Commit and push build artifacts
      #   run: |
      #     git add .
      #     git commit -m "Add build artifacts"
      #     git push origin deploy