name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # - name: Setup Node.js
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: '14.21.3'

    # - name: Update npm packages
    #   run: npm install -g npm@latest

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build  

    # - name: Debug Information
    #   run: |
    #     echo "Node.js version: $(node -v)"
    #     echo "npm version: $(npm -v)"
    #     ls -la
    #     npm run build


  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Deploy to Server
      run: |
        # Set up SSH key for authentication
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key.pem
        chmod 600 ssh_key.pem

        # Copy build files to Raspberry Pi
        scp -i ssh_key.pem -r dist/* tkml@raspberrypi:/

