name: React App Deployment # name of the workflo

on:
  push:
    branches:
      - main # branch name

jobs:
  deploy-react-to-gh-pages:
    runs-on: ubuntu-latest
    env:
      EXAMPLE: example # environment variable

    steps:
      # checkout the repository content to github runner
      - name: Checkout
        uses: actions/checkout@v2

      # setup nodejs environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "18.16.1"

      # cache the dependencies to speed up the build
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # install dependencies
      - name: Install dependencies
        run: npm i

      # build the react app
      - name: Build
        run: npm run build

      - name: Debug Info
        run: |
          echo "Current Directory: $(pwd)"
          echo "Contents of the Directory: $(ls -la)"
          echo "SSH Private Key Permissions: $(ls -la ${{ secrets.SSH_PRIVATE_KEY }})"
      
      - name: Test SSH Connection
        run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} tkml@raspberrypi.local
      

      # - name: Deploy to Raspberry Pi
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.RASPBERRY_PI_HOST }}
      #     username: ${{ secrets.RASPBERRY_PI_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     source: dist/  # Specify the directory containing build artifacts
      #     target: /
      